# Github SOP 

## Adding a Chapter to this site. 

### Adding the RMarkdown File Locally
1. In the local Data Request folder for the Mesulam Center Data Management
Practices site, open the .Rproj file. Create a new r Markdown file and save it 
in the following format: \n
chapter number-title.Rmd (ex: 06-github-sop.Rmd)

2. Add Headings: \n
A single # is used to title the chapter page. (Github SOP at the top of the page) \n
## Double ## is used for a Heading and Section Title in the Table of Contents on 
the right hand side. \n
### Triple ### is used for a Subheading and Sub-section Title in the Table of Contents 
on the right hand side. \n
Note: Github and Bookdown automatically numbers the Table of contents based on the 
saved name of the R Markdown file. 

3. Add desired body of text. 

4. Save the Rmarkdown file. Close the file and open the project file in RStudio. 

### Render the Project Locally
5. To render the book, click 'Build Book' in the Build tab of the Environment
Tabs or run the following command: \n
bookdown::render_book("index.Rmd")
<b>Note: Do not copy and paste from the HTML, it will not work.<b/>   
6. To view the book in html format, run the following command: 
browseURL("docs/index.html")
<b>Note: Do not copy and paste from the HTML, it will not work.<b/>  
7. Confirm all changes were successfully rendered. 

### Commit the Changes
8. Open GitHub Desktop. Confirm you are on the correct Repository. 
9. Click the 'Fetch Origin' button to view local changes that are to be committed. 
10. Review changes, and if everything looks correct, add a summary and click 
'Commit to main'. 
11. Open github.com in a new browser window and go to the desired Repository. 
12. Click on the 'Actions' tab at the top of the page. 
13. A new workflow will run, titled 'pages build and deployment'. To view
progress, click on the action. You will see a pipeline with the build's progress. 
If there are no errors, all three steps will have green checkboxes. 
14. When workflow is complete, click the link under 'deploy' to view the changes
made to the site. 

### For additional information, access the README.md file in the Project folder. 